---
# tasks file for ansible-fluentbit

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - fluentbit
  tags:
    - always
  when: fluentbit_enabled | default(false)

- name: Include configure tasks
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags:
        - fluentbit
  tags:
    - always
  when: fluentbit_enabled | default(false)
