---
# tasks file for ansible-fluentbit

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: fluentbit_enabled | default(false)
  tags:
    - fluentbit
    - always

- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
  when: fluentbit_enabled | default(false)
  tags:
    - fluentbit
    - fluentbit:configure
    - always
