---
# handlers file for ansible-fluentbit
  
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  listen: "Update apt cache"

- name: Restart fluent-bit
  ansible.builtin.systemd:
    name: fluent-bit
    state: restarted  
  listen: "Restart fluent-bit"
  ignore_errors: "{{ ansible_facts['virtualization_type'] == 'podman' or ansible_facts['virtualization_type'] == 'docker' }}"
