---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: systemd-ubuntu-24.04
    image: jrei/systemd-ubuntu:24.04
    command: /sbin/init
    privileged: true
    systemd: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: noexec,nosuid,size=100m
      /tmp: noexec,nosuid,size=100m
  - name: systemd-debian-11
    image: jrei/systemd-debian:11
    command: /sbin/init
    privileged: true
    systemd: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: noexec,nosuid,size=100m
      /tmp: noexec,nosuid,size=100m
  - name: systemd-debian-12
    image: jrei/systemd-debian:12
    command: /sbin/init
    privileged: true
    systemd: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: noexec,nosuid,size=100m
      /tmp: noexec,nosuid,size=100m

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
