---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to Ansible Galaxy
    runs-on: ubuntu-latest
    if: github.repository == 'devopsworks/ansible-fluentbit'

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible

      - name: Trigger a new import on Ansible Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## Changes in this Release
            
            See the [CHANGELOG.md](CHANGELOG.md) for detailed information about this release.
            
            ## Installation
            
            ```bash
            ansible-galaxy install devopsworks.fluentbit
            ```
            
            ## Usage
            
            ```yaml
            - hosts: servers
              become: yes
              roles:
                - devopsworks.fluentbit
            ```
